name: CI/CD pipline
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare for tests
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install -r requirements.txt
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/calculator:latest
          docker run -p 3001:3001 -d ${{ secrets.DOCKER_USERNAME }}/calculator:latest
          sleep 30
      - name: Run tests
        run: |
          pytest integration_test.py
          pytest component_test.py


  build-and-push:
    needs: [ test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build dockerfile
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/calculator:latest

      - name: Push to dockerhub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push tag to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/calculator:latest
